version: '3'

services:

  gchapp:
    build: .
    container_name: gchapp
    hostname: gchapp
    restart: unless-stopped
    depends_on:
      - gchweb
    environment:
      - TZ=America/New_York
    volumes:
      - ./app:/app
      - ./html:/html


  gchweb:
    image: nginx
    container_name: gchweb
    hostname: gchweb
    restart: unless-stopped
    depends_on:
      - gchapp
    environment:
      - TZ=America/New_York
    expose:
      - 80
    ports:
      - 7777:80
    volumes:
      - ./html:/usr/share/nginx/html

networks:
  default:
    external:
      name: gchnet
