version: '3'

services:

  gchapp:
    build: .
    container_name: gchapp
    hostname: gchapp
    restart: unless-stopped
    depends_on:
      - gchweb
    environment:
      - TZ=America/New_York
    volumes:
      - ./app:/app
      - ./html:/html


  gchweb:
    image: nginx
    container_name: gchweb
    hostname: gchweb
    restart: unless-stopped
    depends_on:
      - gchapp
    environment:
      - TZ=America/New_York
    expose:
      - 80
    ports:
      - 7777:80
    volumes:
      - ./html:/usr/share/nginx/html


  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    hostname: npm
    restart: unless-stopped
    depends_on:
      - gchapp
      - gchweb
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    depends_on:
      - npm
    ports:
      - '9443:9443'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data


volumes:
  npm-data:
    name: npm-data
  npm-letsencrypt:
    name: npm-letsencrypt
  portainer-data:
    name: portainer-data

networks:
  default:
    external:
      name: gchnet
